## 异常处理

### JVC发现的异常

当JVC发现程序运行时出现了不能执行的操作，就会抛出(throw)异常(exception)。

比如，使用Scanner输入整数的时候，用户实际上输入了浮点数：

```java
Scanner input = new Scanner(System.in);
//有可能会有：Exception in thread "main" java.util.InputMismatchException
int i = input.nextInt();
System.out.println("your input is: " + i);
```

又比如，当计算两个数相除的时候，除数为0：

```java
int i = 9/0; //java.lang.ArithmeticException: / by zero
```

```java
Scanner input = new Scanner(System.in);
int a = input.nextInt();
int b = input.nextInt();
int i = a/b;
```

堂上练习：

还有当打开一个不存在的文件：

```java
File file = new File("/home/lzh/temp/asdfsdf");
Desktop.getDesktop().open(file);
```

### 没有异常处理机制的时代

以前没有异常处理机制，程序通常使用函数（方法）的返回值来说明异常，但这种方式比较落后：

```java
	public static void main(String[] args) throws IOException {
		int[] arrayA = {1,2,3,4,5,6,7}; //7个元素
		int[] arrayB = new int[10];     //10个元素
		copyArray(arrayA, arrayB, 0, 4, 0);
					System.out.println(Arrays.toString(arrayB));
		
	}
	
	public static int copyArray(
			int[] fromArray, //从这个数组拷贝 
			int[] toArray,   //拷贝到这个数组
			int location,    //从这个位置开始拷贝
			int count,       //拷贝多少个元素
			int toLocation) { //拷贝到那个数据的位置
		if (location >= fromArray.length)
			return -1; //-1说明的是location出错
		else if(location+count > fromArray.length)
			return -2; //-2说明count太多，拷不了那么多
		//……说明有各种异常。。。
		
		for (int i = 0; i<count; i++) {
			toArray[toLocation + i] = fromArray[location+i];
		}
		return 0;  //0说明 没问题
	}
```

问题：

如何在多层函数调用中传递异常？

如何通过返回值带回更多的信息？

相同类型的异常在不同函数中出现，如何复用代码？

这些都是异常处理机制出现的原因。

### 两类异常

异常有两大类，它们都是Exception类的扩展类：

（1）RuntimeException运行期异常。Java允许不检查这类异常，但万一出现，程序将异常终止。这种异常有很多扩展类：

* NumberFormatException: 转换字符串为其它数据时可能出现这种异常；
* NullPointerException：当使用一个引用对象的变量时可能出现这种异常；
* ArrayIndexOutOfBoundsException：使用下标访问数组时下标越界，类似的还有StringIndexOutOfBoundsException；
* ClassCastException转换对象的类型时出错。
* 还有很多……

```java
//NumberFormatException
int i = Integer.parseInt("123abc");
String str = null;

//NullPointerException
System.out.println(str.length());

//ClassCastException
String str = "abc";
Object o = str;
Integer i = (Integer) o;
```

（2）其它非RuntimeException，JVM要求必须检查。种类非常繁杂，常见有：

* IOException：通用的输入输出的异常
* SQLException：操作数据库时的异常
* ClassNotFoundException：要找一个类定义时，找不到的异常


### 异常的处理方法

（1） 不处理(只能对于RuntimeException)：后果可能很严重，程序会因异常终止运行。

```java
int[] array = new int[10];
//java.lang.ArrayIndexOutOfBoundsException
System.out.println(array[10]);
System.out.println("after array[10]");
```

输出“after array[10]”是无法走到的，因为程序在上面一行就已经结束执行了。

（2）在本地处理：try和catch。

```java
		try {
			System.out.println(array[10]);
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("after array[10]");
```

这里处理异常，输出“after array[10]”是可以看到的

（3）抛给上层代码处理。

```java
	public static void fun() throws Exception{
		int[] array = new int[10];
		System.out.println(array[10]);		
		System.out.println("after array[10]");
	}
```

这就好比现实世界中，在工作时发现了问题：不处理，后果很严重；自己处理，如果可能的话，不给大家添麻烦；自己无法处理或不合适处理，则抛给别人处理。

异常处理机制最值得称道的是它可以**分离异常发现和异常处理的代码**。也就是发现了异常，但不一定当场解决：

当计算的代码和界面代码分开编写时：

```java
public class CalcBackEnd {
	
	public static double divide(double a, double b) throws Exception{
		
		if (b == 0)
			throw new Exception("除数不能为0");		
		return a/b;
	}

}

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Calc extends JFrame{
	
	JTextField numAField = new JTextField(4);
	JTextField numBField = new JTextField(4);
	JButton calcButton = new JButton("=");
	JLabel resultLable = new JLabel("  ");
	
	public Calc() {
		this.setLayout(new FlowLayout());
		this.add(numAField);
		this.add(new JLabel("/"));
		this.add(numBField);
		this.add(calcButton);
		this.add(resultLable);
		
		calcButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				double numA = 0;
				double numB = 0;
				try {
					numA = Double.parseDouble(numAField.getText());
					numB = Double.parseDouble(numBField.getText());
					resultLable.setText("" + CalcBackEnd.divide(numA, numB));
				} catch (NumberFormatException e) {
					JOptionPane.showMessageDialog(null, "输入必须为数字");
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, e.getMessage());
				}
			}
		});
		
		this.pack();
		this.setVisible(true);
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setLocationRelativeTo(null);
	}

	public static void main(String[] args) {
		new Calc();
	}

}
```

特别是，当网络出错时，要通知界面；数据库访问出错时，要通知界面……

